In [9]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import math
from __future__ import division
liv = pd.read_csv("C:/Users/win7/Downloads/liverpoolucl.csv")
rm = pd.read_csv("C:/Users/win7/Downloads/realmadriducl.csv")

In [10]:
liv

SNO              HTEAM              ATEAM  HTSCO  ATSCO
0     1         HOFFENHEIM          LIVERPOOL      1      2
1     2          LIVERPOOL         HOFFENHEIM      4      2
2     3    MANCHESTER CITY          LIVERPOOL      5      0
3     4          LIVERPOOL            SEVILLA      2      2
4     5     SPARTAK MOSCOW          LIVERPOOL      1      1
5     6          LIVERPOOL  MANCHESTER UNITED      0      0
6     7            MARIBOR          LIVERPOOL      0      7
7     8          TOTTENHAM          LIVERPOOL      4      1
8     9          LIVERPOOL            MARIBOR      3      0
9    10            SEVILLA          LIVERPOOL      3      3
10   11          LIVERPOOL            CHELSEA      1      1
11   12          LIVERPOOL     SPARTAK MOSCOW      7      0
12   13          LIVERPOOL    MANCHESTER CITY      4      3
13   14          LIVERPOOL          TOTTENHAM      2      2
14   15              PORTO          LIVERPOOL      0      5
15   16          LIVERPOOL              PORTO      0      0
16   17  MANCHESTER UNITED          LIVERPOOL      2      1
17   18          LIVERPOOL    MANCHESTER CITY      3      0
18   19    MANCHESTER CITY          LIVERPOOL      1      2
19   20          LIVERPOOL              ROMA       5      2
20   21               ROMA          LIVERPOOL      4      2
21   22            CHELSEA          LIVERPOOL      1      0

In [11]:
rm

SNO            HTEAM            ATEAM  HTSCO  ATSCO
0     1      REAL MADRID         VALENCIA      2      2
1     2      REAL MADRID            APOEL      3      0
2     3         DORTMUND      REAL MADRID      1      3
3     4      REAL MADRID        TOTTENHAM      1      1
4     5        TOTTENHAM      REAL MADRID      3      1
5     6  ATLETICO MADRID      REAL MADRID      0      0
6     7            APOEL      REAL MADRID      0      6
7     8      REAL MADRID         DORTMUND      3      2
8     9      REAL MADRID          SEVILLA      5      0
9    10      REAL MADRID        BARCELONA      0      3
10   11         VALENCIA      REAL MADRID      1      4
11   12      REAL MADRID              PSG      3      1
12   13              PSG      REAL MADRID      1      2
13   14         JUVENTUS      REAL MADRID      0      3
14   15      REAL MADRID  ATLETICO MADRID      1      1
15   16      REAL MADRID         JUVENTUS      1      3
16   17    BAYERN MUNICH      REAL MADRID      1      2
17   18      REAL MADRID    BAYERN MUNICH      2      2
18   19        BARCELONA      REAL MADRID      2      2
19   20          SEVILLA      REAL MADRID      3      2

In [12]:
hf_attack_liv = liv.loc[(liv["HTEAM"]=="LIVERPOOL"), ["HTSCO"]]
home_games_liv = len(hf_attack_liv.index)
home_goals_scored_liv = sum(hf_attack_liv["HTSCO"])
hf_defence_liv = liv.loc[(liv["HTEAM"]=="LIVERPOOL"), ["ATSCO"]]
home_goals_conceded_liv = sum(hf_defence_liv["ATSCO"])
af_attack_liv = liv.loc[(liv["ATEAM"]=="LIVERPOOL"), ["ATSCO"]]
away_games_liv = len(af_attack_liv.index)
away_goals_scored_liv = sum(af_attack_liv["ATSCO"])
af_defence_liv = liv.loc[(liv["ATEAM"]=="LIVERPOOL"), ["HTSCO"]]
away_goals_conceded_liv = sum(af_defence_liv["HTSCO"])
print "Goals scored at home =",home_goals_scored_liv
print "Goals conceded at home =",home_goals_conceded_liv
print "Goals scored by liverpool away from home =",away_goals_scored_liv 
print "Goals conceded by liverpool away from home =",away_goals_conceded_liv

Goals scored at home = 31
Goals conceded at home = 12
Goals scored by liverpool away from home = 24
Goals conceded by liverpool away from home = 22


In [13]:
hf_attack_rm = rm.loc[(rm["HTEAM"]=="REAL MADRID"), ["HTSCO"]]
home_games_rm = len(hf_attack_rm.index)
home_goals_scored_rm = sum(hf_attack_rm["HTSCO"])
hf_defence_rm = rm.loc[(rm["HTEAM"]=="REAL MADRID"), ["ATSCO"]]
home_goals_conceded_rm = sum(hf_defence_rm["ATSCO"])
af_attack_rm = rm.loc[(rm["ATEAM"]=="REAL MADRID"), ["ATSCO"]]
away_games_rm = len(af_attack_rm.index)
away_goals_scored_rm = sum(af_attack_rm["ATSCO"])
af_defence_rm = rm.loc[(rm["ATEAM"]=="REAL MADRID"), ["HTSCO"]]
away_goals_conceded_rm = sum(af_defence_rm["HTSCO"])
print "Goals scored by Real Madrid at home =",home_goals_scored_rm
print "Goals conceded by Real Madrid at home =",home_goals_conceded_rm
print "Goals scored by Real Madrid away from home =",away_goals_scored_rm
print "Goals conceded by Real Madrid away from home =",away_goals_conceded_rm

Goals scored by Real Madrid at home = 21
Goals conceded by Real Madrid at home = 15
Goals scored by Real Madrid away from home = 25
Goals conceded by Real Madrid away from home = 12


In [15]:
avg_goals_scored_home_liv = round(float(home_goals_scored_liv/home_games_liv), 4)
avg_goals_conceded_home_liv = round(float(home_goals_conceded_liv/home_games_liv), 4)
avg_goals_scored_away_liv = round(float(away_goals_scored_liv/away_games_liv), 4)
avg_goals_conceded_away_liv = round(float(away_goals_conceded_liv/away_games_liv), 4) 
avg_goals_scored_home_liv, avg_goals_conceded_home_liv, avg_goals_scored_away_liv, avg_goals_conceded_away_liv

(2.8182, 1.0909, 2.1818, 2.0)

In [16]:
avg_goals_scored_home_rm = round(float(home_goals_scored_rm/home_games_rm), 4)
avg_goals_conceded_home_rm = round(float(home_goals_conceded_rm/home_games_rm), 4)
avg_goals_scored_away_rm = round(float(away_goals_scored_rm/away_games_rm), 4)
avg_goals_conceded_away_rm = round(float(away_goals_conceded_rm/away_games_rm), 4) 
avg_goals_scored_home_rm, avg_goals_conceded_home_rm, avg_goals_scored_away_rm, avg_goals_conceded_away_rm

(2.1, 1.5, 2.5, 1.2)

In [88]:
goals_scored_home_cl = 220
goals_conceded_home_cl = 177 
goals_scored_away_cl = 177 
goals_conceded_away_cl = 220 
total_games_cl = 124
avg_goals_scored_home_cl = round(float(goals_scored_home_cl/total_games_cl), 4)
avg_goals_conceded_home_cl = round(float(goals_conceded_home_cl/total_games_cl), 4)
avg_goals_scored_away_cl = round(float(goals_scored_away_cl/total_games_cl), 4)
avg_goals_conceded_away_cl = round(float(goals_conceded_away_cl/total_games_cl), 4)
print avg_goals_scored_home_cl, avg_goals_conceded_home_cl, avg_goals_scored_away_cl, avg_goals_conceded_away_cl

1.7742 1.4274 1.4274 1.7742


In [89]:
rm_attack_strength = round(float(avg_goals_scored_away_rm/avg_goals_scored_away_cl), 4)
liv_defence_strength = round(float(avg_goals_conceded_away_liv/avg_goals_conceded_away_cl), 4) 
liv_attack_strength = round(float(avg_goals_scored_away_liv/avg_goals_scored_away_cl), 4) 
rm_defence_strength = round(float(avg_goals_conceded_away_rm/avg_goals_conceded_away_cl), 4)
print rm_attack_strength, liv_defence_strength, liv_attack_strength, rm_defence_strength

1.7514 1.1273 1.5285 0.6764


In [90]:
projected_goals_rm = round((rm_attack_strength*liv_defence_strength*avg_goals_scored_away_cl), 4) 
projected_goals_liv = round((liv_attack_strength*rm_defence_strength*avg_goals_scored_away_cl), 4)
print projected_goals_rm, "-", projected_goals_liv  

2.8182 - 1.4758


In [91]:
i = 0
print "         ", "Poisson % for the number of goals scored"
print "-----------------------------------------------------"
print "Goals", "Real Madrid", "Liverpool"
for i in range(0,6):
    print " ", (i), "     ", (round((((projected_goals_rm**i)*math.exp(-projected_goals_rm))/math.factorial(i)), 4)*100), "   ",(round((((projected_goals_liv**i)*math.exp(-projected_goals_liv))/math.factorial(i)), 4)*100)

          Poisson % for the number of goals scored
-----------------------------------------------------
Goals Real Madrid Liverpool
  0       5.97     22.86
  1       16.83     33.74
  2       23.71     24.89
  3       22.28     12.25
  4       15.69     4.52
  5       8.85     1.33


In [92]:
rmarr = [0] * 6
livarr = [0] * 6
i = 0
for i in range(0,6): 
    rmarr[i] = round(((((projected_goals_rm**i)*math.exp(-projected_goals_rm))/math.factorial(i))*100), 2)
    livarr[i] = round(((((projected_goals_liv**i)*math.exp(-projected_goals_liv))/math.factorial(i))*100), 2)

for i in range(0,6):
    print (rmarr[i]), 


5.97 16.83 23.71 22.28 15.69 8.85


IndexError: list index out of range

In [93]:
pos = np.ones((7,7))
i = 1 
for i in range(len(pos)):
    pos[:1,i] = rmarr[i-1]

for i in range(len(pos)):
    pos[i,:1] = livarr[i-1]
pos[:1,:1] = 0
print(pos)

[[  0.     5.97  16.83  23.71  22.28  15.69   8.85]
 [ 22.86   1.     1.     1.     1.     1.     1.  ]
 [ 33.74   1.     1.     1.     1.     1.     1.  ]
 [ 24.89   1.     1.     1.     1.     1.     1.  ]
 [ 12.25   1.     1.     1.     1.     1.     1.  ]
 [  4.52   1.     1.     1.     1.     1.     1.  ]
 [  1.33   1.     1.     1.     1.     1.     1.  ]]


In [94]:
i = 1
j = 1
for i in range(1,7):
    for j in range(1,7):
        pos[i,j] = round(((pos[i,0]*pos[0,j])/100),2)
        
print(pos)

[[  0.     5.97  16.83  23.71  22.28  15.69   8.85]
 [ 22.86   1.36   3.85   5.42   5.09   3.59   2.02]
 [ 33.74   2.01   5.68   8.     7.52   5.29   2.99]
 [ 24.89   1.49   4.19   5.9    5.55   3.91   2.2 ]
 [ 12.25   0.73   2.06   2.9    2.73   1.92   1.08]
 [  4.52   0.27   0.76   1.07   1.01   0.71   0.4 ]
 [  1.33   0.08   0.22   0.32   0.3    0.21   0.12]]


In [95]:
i = 0
j = 0 
for i in range(0,7):
    pos[:1,i] = 0
    pos[i,:1] = 0
print(pos)

[[ 0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.36  3.85  5.42  5.09  3.59  2.02]
 [ 0.    2.01  5.68  8.    7.52  5.29  2.99]
 [ 0.    1.49  4.19  5.9   5.55  3.91  2.2 ]
 [ 0.    0.73  2.06  2.9   2.73  1.92  1.08]
 [ 0.    0.27  0.76  1.07  1.01  0.71  0.4 ]
 [ 0.    0.08  0.22  0.32  0.3   0.21  0.12]]


In [96]:
draw_percentage = 0
i = 0 
j = 0
for i in range(len(pos)):
    for j in range(len(pos)):
        if(i==j):
            draw_percentage += pos[i,j]
            
print "Draw Percentage =", draw_percentage

Draw Percentage = 16.5


In [97]:
rm_win_percentage = 0
i = 0 
j = 0
for i in range(len(pos)):
    for j in range(len(pos)):
        if(i<j):
            rm_win_percentage += pos[i,j]

print "Real Madrid Win Pecentage =", rm_win_percentage 

58.829999999999991

In [98]:
liv_win_percentage = 0
i = 0 
j = 0
for i in range(len(pos)):
    for j in range(len(pos)):
        if(i>j):
            liv_win_percentage += pos[i,j]
liv_win_percentage 

17.620000000000001

In [99]:
sum_x = 0
for i in range(0,7):
    for j in range(0,7):
        if (i>j or i<j or i==j):
            sum_x += pos[i,j]
                    
print sum_x, draw_percentage + rm_win_percentage + liv_win_percentage 

92.95 92.95


In [103]:
pos = np.delete(pos, (0), axis=0)
pos = np.delete(pos, (0), axis=1)
print(pos)

[[ 1.36  3.85  5.42  5.09  3.59  2.02]
 [ 2.01  5.68  8.    7.52  5.29  2.99]
 [ 1.49  4.19  5.9   5.55  3.91  2.2 ]
 [ 0.73  2.06  2.9   2.73  1.92  1.08]
 [ 0.27  0.76  1.07  1.01  0.71  0.4 ]
 [ 0.08  0.22  0.32  0.3   0.21  0.12]]


In [137]:
max_num = pos.max()
i = 0 
j = 0 
for i in range(len(pos)):
    for j in range(len(pos)):
        if(pos[i,j]==max_num):
            print "Real Madrid ",j,"-",i, "Liverpool"
            
            

Real Madrid  2 - 1 Liverpool
